version: "3"
services:
  front:
    image: node:lts-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev -- --host
    expose:
      - "5173"
    ports:
      - "5173:5173"
