version: '3'
services:
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "${APP_PORT:-80}:8080"
        environment:
            WWWUSER: "${WWWUSER}"
        networks:
            - api-network
        volumes:
            - .:/app
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${MYSQL_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-password}"
            MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST:-%}"
            MYSQL_DATABASE: "${DB_DATABASE:-talk}"
            MYSQL_USER: "${DB_USERNAME:-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
        networks:
            - api-network
        volumes:
            - "mysql-db:/var/lib/mysql"
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 10
            timeout: 1s

networks:
    api-network:
        driver: bridge

volumes:
    mysql-db:
        driver: local
